### ISSUE TITLE
源码的使用和访客数据的问题。

### ISSUE THREAD

**Issue by anyi98** [BYR-Navi/BYR-Navi#46]
你好。非常感谢密你能够在此开源。可供众人享用。

我在使用此开源时。遇到了两个问题。如题。
在提问之前已经看过该项目问题的回答。略有些启迪。

了解到此开源在G page 上可以正常使用，是因为此基于Jekyll
  看了文档，也下载了J 。 

若脱离G page 使用。
不知道渲染方式 是整包渲染还是单文件渲染。

至于，Matomo的统计。  我是在它的网页端上使用。
在_data里修改了matomo的数据。  可还是获取不到访客人数。
是需要添加追踪代码还是配置信息有误？。

问题如上。望能给予解答。

[GitHub](https://github.com/anyi98/anyi98.github.io)
[导航网页](https://anyi.life)

**Comment by iROCKBUNNY** [comment]
1. If you want to host your website on your own machine, one simple way is to upload the `_site` directory (generated by Jekyll's `jekyll build` command) to your (production) machine/server, and adopt a reverse proxy (e.g. NGINX, Apache) to host it from that directory as a static website.
2. For usage questions with respect to Matomo, please refer to Matomo's official docs to obtain an ultimate solution. However, I may give you one hint here - you may need a server to deploy your own Matomo service, in order to obtain analytic data of your website.
3. Good luck.

**Comment by anyi98** [comment]
Thank you for your answer.   Those problems are being solved.

**Comment by seramat** [comment]
> Thank you for your answer. Those problems are being solved.

I have got the same problem. How did you solve the problem?
