### ISSUE TITLE
加载不正常，需要刷新才能完全加载

### ISSUE THREAD

**Issue by ryanxia0226** [BYR-Navi/BYR-Navi#53]
![微信图片编辑_20210219180801](https://user-images.githubusercontent.com/42346721/108490196-6e5f2480-72dd-11eb-9989-e7f2f7bff230.jpg)
你好，请问一下我把导航设定为浏览器的默认起始页，打开有时会如图那样加载不正常，需要重新刷新才正常加载，这个是浏览器的问题，还是服务器端的问题呢？我服务器端是通过ruby生成的site静态布置的。

**Comment by iROCKBUNNY** [comment]
@ryanxia0226 I've visited you deployed site on `https://xiacong.link/` and it works fine for my Chrome 88 on macOS. The issue appeared on your website might be caused by missing corresponding style sheets (aka. `*.css` files). By default, most assets are hosted via CDN, which is the `unpkg.com` in this project. My suggestions are either change a faster CDN, or host those assets on your website server.
